name: Nuget package release

env:
  project: 'src/Argutec.Profiling/Argutec.Profiling.csproj'

on:
  create:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "${{env.project}}"
    - name: Build
      run: dotnet build "${{env.project}}" --configuration Release --no-restore
    - name: Test
      run: dotnet test "${{env.project}}" --no-restore --verbosity normal
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Pack Nuget package
      run: dotnet pack "${{env.project}}" --configuration Release -p:PackageVersion=$RELEASE_VERSION
    - name: Push Nuget package
      run: dotnet nuget push **/*.nupkg
            --api-key "${{ secrets.TOKEN }}"
            --source "https://api.nuget.org/v3/index.json"